//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appointment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_medicines
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public m_medicines()
        {
            this.m_order_details = new HashSet<m_order_details>();
            this.s_Prescription = new HashSet<s_Prescription>();
        }
    
        public int medid { get; set; }
        public string name { get; set; }
        public string image { get; set; }
        public Nullable<int> medtypeid { get; set; }
        public Nullable<int> catid { get; set; }
        public Nullable<int> m_supid { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> quantity_in_stock { get; set; }
    
        public virtual m_categories m_categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<m_order_details> m_order_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<s_Prescription> s_Prescription { get; set; }
        public virtual m_suppliers m_suppliers { get; set; }
        public virtual m_types m_types { get; set; }
    }
}
