//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appointment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class s_LabTestPrescription
    {
        public int LabTestPrescriptionID { get; set; }
        public int LabTestID { get; set; }
        public int PrescriptionID { get; set; }
    
        public virtual s_LabTest s_LabTest { get; set; }
        public virtual s_Prescription s_Prescription { get; set; }
    }
}
