//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appointment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class s_Product
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string image { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public int QuantityInStock { get; set; }
    
        public virtual s_Category s_Category { get; set; }
        public virtual s_Supplier s_Supplier { get; set; }
    }
}
