//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelleryShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUsers2
    {
        public string Id { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string NormalizedUserName { get; set; }
        public string AccessFailedCount { get; set; }
        public string ConcurrencyStamp { get; set; }
        public string EmailConfirmed { get; set; }
        public string LockoutEnabled { get; set; }
        public string LockoutEnd { get; set; }
        public string NormalizedEmail { get; set; }
        public string PasswordHash { get; set; }
        public string PhoneNumberConfirmed { get; set; }
        public string SecurityStamp { get; set; }
        public string TwoFactorEnabled { get; set; }
        public string UserName { get; set; }
    }
}
