//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelleryShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CITY
    {
        public CITY()
        {
            this.CUSTOMERs = new HashSet<CUSTOMER>();
        }
    
        public int CITY_ID { get; set; }
        public string CITY_NAME { get; set; }
        public Nullable<int> COUNTRY_ID { get; set; }
    
        public virtual COUNTRY COUNTRY { get; set; }
        public virtual ICollection<CUSTOMER> CUSTOMERs { get; set; }
    }
}
