//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelleryShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COUNTRY
    {
        public COUNTRY()
        {
            this.CITies = new HashSet<CITY>();
            this.CUSTOMERs = new HashSet<CUSTOMER>();
        }
    
        public int COUNTRY_ID { get; set; }
        public string COUNTRY_NAME { get; set; }
    
        public virtual ICollection<CITY> CITies { get; set; }
        public virtual ICollection<CUSTOMER> CUSTOMERs { get; set; }
    }
}
