//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelleryShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public CUSTOMER()
        {
            this.LOGINs = new HashSet<LOGIN>();
        }
    
        public int CUSTOMER_ID { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string EMAIL_ID { get; set; }
        public Nullable<int> COUNTRY_ID { get; set; }
        public Nullable<int> CITY_ID { get; set; }
        public Nullable<int> PIN_CODE { get; set; }
        public string KEYWORD { get; set; }
        public string ADDRESS { get; set; }
    
        public virtual CITY CITY { get; set; }
        public virtual COUNTRY COUNTRY { get; set; }
        public virtual ICollection<LOGIN> LOGINs { get; set; }
    }
}
