//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelleryShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGIN
    {
        public int LOGIN_ID { get; set; }
        public string USER_NAME { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public string MEM_TYPE { get; set; }
        public string ACTIVE { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
