//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelleryShop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class NorthwindEntities : DbContext
    {
        public NorthwindEntities()
            : base("name=NorthwindEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public DbSet<AspNetRoleClaim> AspNetRoleClaims { get; set; }
        public DbSet<AspNetRole> AspNetRoles { get; set; }
        public DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public DbSet<AspNetUser> AspNetUsers { get; set; }
        public DbSet<AspNetUsers2> AspNetUsers2 { get; set; }
        public DbSet<AspNetUserToken> AspNetUserTokens { get; set; }
        public DbSet<CartLine> CartLines { get; set; }
        public DbSet<CITY> CITies { get; set; }
        public DbSet<COUNTRY> COUNTRies { get; set; }
        public DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public DbSet<CustomerDemographic> CustomerDemographics { get; set; }
        public DbSet<Customer1> Customers1 { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<LOGIN> LOGINs { get; set; }
        public DbSet<Order_Detail> Order_Details { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<Orders2> Orders2 { get; set; }
        public DbSet<Productsbkp> Productsbkps { get; set; }
        public DbSet<Region> Regions { get; set; }
        public DbSet<SCartLine> SCartLines { get; set; }
        public DbSet<Shipper> Shippers { get; set; }
        public DbSet<SOrder> SOrders { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Territory> Territories { get; set; }
    
        public virtual int REGISTRATION(string cUSTOMER_NAME, string eMAIL_ID, Nullable<int> cOUNTRY_ID, Nullable<int> cITY_ID, Nullable<int> pIN_CODE, string kEYWORD, string aDDRESS, ObjectParameter eMAIL_ID_OUT, string pWD, ObjectParameter cUSTOMER_ID)
        {
            var cUSTOMER_NAMEParameter = cUSTOMER_NAME != null ?
                new ObjectParameter("CUSTOMER_NAME", cUSTOMER_NAME) :
                new ObjectParameter("CUSTOMER_NAME", typeof(string));
    
            var eMAIL_IDParameter = eMAIL_ID != null ?
                new ObjectParameter("EMAIL_ID", eMAIL_ID) :
                new ObjectParameter("EMAIL_ID", typeof(string));
    
            var cOUNTRY_IDParameter = cOUNTRY_ID.HasValue ?
                new ObjectParameter("COUNTRY_ID", cOUNTRY_ID) :
                new ObjectParameter("COUNTRY_ID", typeof(int));
    
            var cITY_IDParameter = cITY_ID.HasValue ?
                new ObjectParameter("CITY_ID", cITY_ID) :
                new ObjectParameter("CITY_ID", typeof(int));
    
            var pIN_CODEParameter = pIN_CODE.HasValue ?
                new ObjectParameter("PIN_CODE", pIN_CODE) :
                new ObjectParameter("PIN_CODE", typeof(int));
    
            var kEYWORDParameter = kEYWORD != null ?
                new ObjectParameter("KEYWORD", kEYWORD) :
                new ObjectParameter("KEYWORD", typeof(string));
    
            var aDDRESSParameter = aDDRESS != null ?
                new ObjectParameter("ADDRESS", aDDRESS) :
                new ObjectParameter("ADDRESS", typeof(string));
    
            var pWDParameter = pWD != null ?
                new ObjectParameter("PWD", pWD) :
                new ObjectParameter("PWD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("REGISTRATION", cUSTOMER_NAMEParameter, eMAIL_IDParameter, cOUNTRY_IDParameter, cITY_IDParameter, pIN_CODEParameter, kEYWORDParameter, aDDRESSParameter, eMAIL_ID_OUT, pWDParameter, cUSTOMER_ID);
        }
    }
}
