//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelleryShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productsbkp
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string QuantityPerUnit { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<short> UnitsInStock { get; set; }
        public Nullable<short> UnitsOnOrder { get; set; }
        public Nullable<short> ReorderLevel { get; set; }
        public bool Discontinued { get; set; }
        public string image { get; set; }
        public Nullable<int> LOC_ID { get; set; }
        public Nullable<int> SH_ID { get; set; }
        public Nullable<int> ROW_NO { get; set; }
        public Nullable<int> COL_NO { get; set; }
        public byte[] dbimage { get; set; }
        public string ImageMimeType { get; set; }
        public string tr_type { get; set; }
        public Nullable<System.DateTime> tr_date { get; set; }
    }
}
