//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appointment.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProvidenceClinicsEntities : DbContext
    {
        public ProvidenceClinicsEntities()
            : base("name=ProvidenceClinicsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<e_class> e_class { get; set; }
        public virtual DbSet<e_enrollments> e_enrollments { get; set; }
        public virtual DbSet<e_lsp> e_lsp { get; set; }
        public virtual DbSet<e_lsp_type> e_lsp_type { get; set; }
        public virtual DbSet<e_staff> e_staff { get; set; }
        public virtual DbSet<e_staff_type> e_staff_type { get; set; }
        public virtual DbSet<e_students> e_students { get; set; }
        public virtual DbSet<e_subject> e_subject { get; set; }
        public virtual DbSet<m_categories> m_categories { get; set; }
        public virtual DbSet<m_customers> m_customers { get; set; }
        public virtual DbSet<m_medicines> m_medicines { get; set; }
        public virtual DbSet<m_order_details> m_order_details { get; set; }
        public virtual DbSet<m_orders> m_orders { get; set; }
        public virtual DbSet<m_suppliers> m_suppliers { get; set; }
        public virtual DbSet<m_types> m_types { get; set; }
        public virtual DbSet<Register> Registers { get; set; }
        public virtual DbSet<RegisterType> RegisterTypes { get; set; }
        public virtual DbSet<s_Appointment> s_Appointment { get; set; }
        public virtual DbSet<s_AppointmentDetail> s_AppointmentDetail { get; set; }
        public virtual DbSet<s_Category> s_Category { get; set; }
        public virtual DbSet<s_Contact> s_Contact { get; set; }
        public virtual DbSet<s_Doctor> s_Doctor { get; set; }
        public virtual DbSet<s_DoctorSchedule> s_DoctorSchedule { get; set; }
        public virtual DbSet<s_Feedback> s_Feedback { get; set; }
        public virtual DbSet<s_LabTest> s_LabTest { get; set; }
        public virtual DbSet<s_LabTestPrescription> s_LabTestPrescription { get; set; }
        public virtual DbSet<s_Order> s_Order { get; set; }
        public virtual DbSet<s_OrderDetail> s_OrderDetail { get; set; }
        public virtual DbSet<s_Patient> s_Patient { get; set; }
        public virtual DbSet<s_PatientHistory> s_PatientHistory { get; set; }
        public virtual DbSet<s_Prescription> s_Prescription { get; set; }
        public virtual DbSet<s_Product> s_Product { get; set; }
        public virtual DbSet<s_Specialist> s_Specialist { get; set; }
        public virtual DbSet<s_Status> s_Status { get; set; }
        public virtual DbSet<s_Supplier> s_Supplier { get; set; }
        public virtual DbSet<s_Transaction> s_Transaction { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
