//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appointment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class s_LabTest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public s_LabTest()
        {
            this.s_LabTestPrescription = new HashSet<s_LabTestPrescription>();
        }
    
        public int LabTestID { get; set; }
        public string TestName { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public string TestDate { get; set; }
        public string ChemicalsUsed { get; set; }
        public string LabProductsUsed { get; set; }
        public decimal Cost { get; set; }
        public decimal Price { get; set; }
    
        public virtual s_Doctor s_Doctor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<s_LabTestPrescription> s_LabTestPrescription { get; set; }
        public virtual s_Patient s_Patient { get; set; }
    }
}
