//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvidenceClinics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class e_enrollments
    {
        public int enid { get; set; }
        public Nullable<int> regid { get; set; }
        public Nullable<int> stdid { get; set; }
        public Nullable<int> classid { get; set; }
        public Nullable<int> subid { get; set; }
        public Nullable<int> lspid { get; set; }
        public Nullable<int> proid { get; set; }
        public string enrollment_date { get; set; }
        public Nullable<decimal> fee { get; set; }
    
        public virtual e_class e_class { get; set; }
        public virtual e_lsp e_lsp { get; set; }
        public virtual e_students e_students { get; set; }
        public virtual e_staff e_staff { get; set; }
        public virtual e_subject e_subject { get; set; }
    }
}
