//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvidenceClinics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class e_staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public e_staff()
        {
            this.e_enrollments = new HashSet<e_enrollments>();
        }
    
        public int proid { get; set; }
        public Nullable<int> regid { get; set; }
        public string name { get; set; }
        public string image { get; set; }
        public Nullable<int> stype_id { get; set; }
        public string qualification { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<e_enrollments> e_enrollments { get; set; }
        public virtual e_staff_type e_staff_type { get; set; }
        public virtual Register Register { get; set; }
    }
}
