//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvidenceClinics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_order_details
    {
        public int odid { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> medicine_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> unit_price { get; set; }
    
        public virtual m_medicines m_medicines { get; set; }
        public virtual m_orders m_orders { get; set; }
    }
}
