//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvidenceClinics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class s_Appointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public s_Appointment()
        {
            this.s_AppointmentDetail = new HashSet<s_AppointmentDetail>();
            this.s_Prescription = new HashSet<s_Prescription>();
        }
    
        public int AppointmentID { get; set; }
        public int PatientID { get; set; }
        public int DoctorID { get; set; }
        public string AppointmentDate { get; set; }
        public string AppointmentTime { get; set; }
        public Nullable<decimal> fee { get; set; }
        public int Statusid { get; set; }
    
        public virtual s_Doctor s_Doctor { get; set; }
        public virtual s_Patient s_Patient { get; set; }
        public virtual s_Status s_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<s_AppointmentDetail> s_AppointmentDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<s_Prescription> s_Prescription { get; set; }
    }
}
