//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvidenceClinics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class s_DoctorSchedule
    {
        public int SchID { get; set; }
        public int DoctorID { get; set; }
        public string AvailableDate { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
    
        public virtual s_Doctor s_Doctor { get; set; }
    }
}
