//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvidenceClinics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class s_PatientHistory
    {
        public int HistoryID { get; set; }
        public int PatientID { get; set; }
        public int DoctorID { get; set; }
        public string VisitDate { get; set; }
        public string VisitTime { get; set; }
        public string Notes { get; set; }
    
        public virtual s_Doctor s_Doctor { get; set; }
        public virtual s_Patient s_Patient { get; set; }
    }
}
