//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvidenceClinics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class s_Prescription
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public s_Prescription()
        {
            this.s_LabTestPrescription = new HashSet<s_LabTestPrescription>();
        }
    
        public int PrescriptionID { get; set; }
        public int AppointmentID { get; set; }
        public int MedicineID { get; set; }
        public string Dosage { get; set; }
        public string Duration { get; set; }
        public string Notes { get; set; }
    
        public virtual m_medicines m_medicines { get; set; }
        public virtual s_Appointment s_Appointment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<s_LabTestPrescription> s_LabTestPrescription { get; set; }
    }
}
