//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvidenceClinics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class s_Specialist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public s_Specialist()
        {
            this.s_Doctor = new HashSet<s_Doctor>();
        }
    
        public int SpecialistID { get; set; }
        public string SpecialistName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<s_Doctor> s_Doctor { get; set; }
    }
}
