//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvidenceClinics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class s_Transaction
    {
        public int TransactionID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int Quantity { get; set; }
        public decimal PurchasePrice { get; set; }
        public decimal SellingPrice { get; set; }
    
        public virtual s_Order s_Order { get; set; }
        public virtual s_Supplier s_Supplier { get; set; }
    }
}
